# Generated by Django 4.0.8 on 2023-04-28 07:08

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование мероприятия')),
                ('image', models.ImageField(blank=True, null=True, upload_to='events_images', verbose_name='Изображение мероприятия')),
                ('is_public', models.BooleanField(default=True, verbose_name='Публичное ли мероприятие')),
                ('venue', models.CharField(blank=True, max_length=200, null=True, verbose_name='Место проведения мероприятия')),
                ('short_information', models.TextField(blank=True, max_length=200, null=True, verbose_name='Краткая информация о мероприятии')),
                ('full_information', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Полная информация о мероприятии')),
                ('registered_visitors', models.PositiveIntegerField(default=0, verbose_name='Текущее кол-во записавшихся посетителей')),
                ('max_visitors', models.PositiveIntegerField(default=0, verbose_name='Максимум посетителей')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления мероприятия')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления мероприятия')),
            ],
            options={
                'verbose_name': 'мероприятие',
                'verbose_name_plural': 'Мероприятия',
                'ordering': ('name',),
            },
        ),
    ]
