# Generated by Django 4.0.8 on 2023-04-28 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivateEvents',
            fields=[
                ('events_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='events.events')),
            ],
            options={
                'verbose_name': 'приватное мероприятие',
                'verbose_name_plural': 'Приватные мероприятия',
                'ordering': ('name',),
            },
            bases=('events.events',),
        ),
        migrations.RemoveField(
            model_name='events',
            name='is_public',
        ),
        migrations.AddField(
            model_name='events',
            name='date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время проведения мероприятия'),
        ),
    ]
