# Generated by Django 4.2.1 on 2023-05-05 11:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="eventregistrations",
            options={
                "verbose_name": "регистрацию на мероприятие",
                "verbose_name_plural": "Регистрации на мероприятия",
            },
        ),
        migrations.AlterModelOptions(
            name="privateeventregistrations",
            options={
                "verbose_name": "регистрацию на приватное мероприятие",
                "verbose_name_plural": "Регистрации на приватные мероприятия",
            },
        ),
        migrations.AlterModelOptions(
            name="privateevents",
            options={
                "ordering": ("name",),
                "verbose_name": "приватное мероприятие",
                "verbose_name_plural": "Приватные мероприятия",
            },
        ),
        migrations.AddField(
            model_name="eventregistrations",
            name="inviting_user_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="ID приглашающего пользователя",
            ),
        ),
        migrations.AddField(
            model_name="privateeventregistrations",
            name="inviting_user_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="ID приглашающего пользователя",
            ),
        ),
    ]
