# Generated by Django 4.2.1 on 2023-05-05 11:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("events", "0002_alter_eventregistrations_options_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="privateeventregistrations",
            name="private_event_user_id_unique",
        ),
        migrations.RenameField(
            model_name="privateeventregistrations",
            old_name="private_event_id",
            new_name="event_id",
        ),
        migrations.AlterUniqueTogether(
            name="privateeventregistrations",
            unique_together={("event_id", "user_id")},
        ),
        migrations.AddConstraint(
            model_name="privateeventregistrations",
            constraint=models.UniqueConstraint(
                fields=("event_id", "user_id"), name="private_event_user_id_unique"
            ),
        ),
    ]
