# Generated by Django 4.0.8 on 2023-04-28 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_privateevents_remove_events_is_public_events_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='events_images/', verbose_name='Изображение мероприятия'),
        ),
    ]
