# Generated by Django 4.0.8 on 2023-04-28 11:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_events_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='duration',
            field=models.DurationField(blank=True, default=datetime.timedelta(seconds=7200), null=True, verbose_name='Длительность мероприятия'),
        ),
        migrations.AddField(
            model_name='events',
            name='visitors_list',
            field=models.JSONField(auto_created=True, blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='image',
            field=models.ImageField(blank=True, default='#', null=True, upload_to='events_images/', verbose_name='Изображение для мероприятия'),
        ),
    ]
