# Generated by Django 4.2.1 on 2023-05-06 17:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0004_paideventregistrations_paidevents_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="paidevents",
            options={
                "ordering": ("name",),
                "verbose_name": "платное мероприятие",
                "verbose_name_plural": "Платные мероприятия",
            },
        ),
    ]
