# Generated by Django 4.2.1 on 2023-05-06 17:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("events", "0005_alter_paidevents_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paidevents",
            name="category_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="events.eventtypes",
                verbose_name="Тип платного мероприятия",
            ),
        ),
        migrations.AlterField(
            model_name="paidevents",
            name="status",
            field=models.TextField(
                blank=True,
                choices=[
                    ("CREATED", "Платеж создан"),
                    ("WAITING", "Платёж в обработке / ожидает оплаты"),
                    ("PAID", "Платёж оплачен"),
                    ("EXPIRED", "Время жизни счета истекло. Счет не оплачен."),
                    ("REJECTED", "Платёж отклонен"),
                ],
                default="CREATED",
                null=True,
                verbose_name="Статус оплаты",
            ),
        ),
        migrations.AlterField(
            model_name="paidevents",
            name="venue_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="events.eventvenues",
                verbose_name="Место проведения платного мероприятия",
            ),
        ),
        migrations.AlterField(
            model_name="paidevents",
            name="visitors",
            field=models.ManyToManyField(
                blank=True,
                through="events.PaidEventRegistrations",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Зарегестрированные на платное мероприятие пользователи",
            ),
        ),
    ]
