# Generated by Django 4.0.8 on 2023-04-29 09:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0006_rename_date_events_start_datetime_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование категории мероприятия')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания категории мероприятия')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления категории мероприятия')),
            ],
            options={
                'verbose_name': 'категорию мероприятия',
                'verbose_name_plural': 'Категории мероприятий',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='EventVenues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование места проведения мероприятия')),
                ('address', models.CharField(blank=True, max_length=200, null=True, verbose_name='Адрес места проведения мероприятия')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='(Координаты) Широта места проведения мероприятия')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='(Координаты) Долгота места проведения мероприятия')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания места проведения мероприятия')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления места проведения мероприятия')),
            ],
            options={
                'verbose_name': 'место проведения мероприятия',
                'verbose_name_plural': 'Места проведения мероприятия',
                'ordering': ('name',),
            },
        ),
        migrations.RenameModel(
            old_name='EventsRegistrations',
            new_name='EventRegistrations',
        ),
        migrations.AlterModelOptions(
            name='eventregistrations',
            options={'verbose_name': 'регистрацию на мероприятие', 'verbose_name_plural': 'Регистрации на мероприятия'},
        ),
    ]
