# Generated by Django 4.2.1 on 2023-05-06 18:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "events",
            "0006_alter_paidevents_category_id_alter_paidevents_status_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="paidevents",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Стоимость регистрации на платное мероприятие",
            ),
            preserve_default=False,
        ),
    ]
