# Generated by Django 4.0.8 on 2023-04-29 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_eventcategories_eventvenues_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование типа мероприятия')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания типа мероприятия')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления типа мероприятия')),
            ],
            options={
                'verbose_name': 'тип мероприятия',
                'verbose_name_plural': 'Типы мероприятий',
                'ordering': ('name',),
            },
        ),
        migrations.DeleteModel(
            name='EventCategories',
        ),
        migrations.RemoveField(
            model_name='events',
            name='venue',
        ),
        migrations.AddField(
            model_name='events',
            name='venue_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='events.eventvenues', verbose_name='Место проведения мероприятия'),
        ),
        migrations.AddField(
            model_name='events',
            name='category_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.eventtypes', verbose_name='Тип мероприятия'),
        ),
    ]
