# Generated by Django 4.2.1 on 2023-05-06 18:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0007_paidevents_price"),
    ]

    operations = [
        migrations.RenameField(
            model_name="paidevents",
            old_name="status",
            new_name="payment_status",
        ),
    ]
