# Generated by Django 4.0.8 on 2023-04-29 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_eventtypes_delete_eventcategories_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventvenues',
            options={'ordering': ('name',), 'verbose_name': 'место проведения мероприятия', 'verbose_name_plural': 'Места проведения мероприятий'},
        ),
        migrations.RenameField(
            model_name='eventregistrations',
            old_name='event',
            new_name='event_id',
        ),
        migrations.RenameField(
            model_name='eventregistrations',
            old_name='user',
            new_name='user_id',
        ),
    ]
