# Generated by Django 4.2.1 on 2023-05-06 18:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0009_alter_paidevents_payment_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="paidevents",
            name="payment_link",
        ),
        migrations.RemoveField(
            model_name="paidevents",
            name="payment_status",
        ),
        migrations.AddField(
            model_name="paideventregistrations",
            name="payment_link",
            field=models.URLField(
                auto_created=True,
                blank=True,
                null=True,
                verbose_name="Ссылка на оплату",
            ),
        ),
        migrations.AddField(
            model_name="paideventregistrations",
            name="payment_status",
            field=models.TextField(
                auto_created=True,
                blank=True,
                choices=[
                    ("CREATED", "Платеж создан"),
                    ("WAITING", "Платёж в обработке / ожидает оплаты"),
                    ("PAID", "Платёж оплачен"),
                    ("EXPIRED", "Время жизни счета истекло. Счет не оплачен."),
                    ("REJECTED", "Платёж отклонен"),
                ],
                default="CREATED",
                null=True,
                verbose_name="Статус оплаты",
            ),
        ),
    ]
