# Generated by Django 4.0.8 on 2023-04-29 22:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0009_alter_eventvenues_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregistrations',
            name='is_invitation_accepted',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Принял ли пользователь приглашение на мероприятие'),
        ),
        migrations.AlterField(
            model_name='eventregistrations',
            name='event_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.events', verbose_name='ID мероприятия'),
        ),
        migrations.AlterField(
            model_name='eventregistrations',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ID пользователя'),
        ),
    ]
