# Generated by Django 4.0.8 on 2023-04-30 15:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0010_eventregistrations_is_invitation_accepted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventvenues',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Координата широты для места проведения мероприятия'),
        ),
        migrations.AlterField(
            model_name='eventvenues',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Координата долготы для места проведения мероприятия'),
        ),
        migrations.AlterUniqueTogether(
            name='eventregistrations',
            unique_together={('event_id', 'user_id')},
        ),
    ]
