# Generated by Django 4.0.8 on 2023-05-01 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_alter_eventvenues_latitude_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='eventregistrations',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='eventregistrations',
            constraint=models.UniqueConstraint(fields=('event_id', 'user_id'), name='event_user_id_unique'),
        ),
    ]
