# Generated by Django 4.2.1 on 2023-05-08 13:30

from django.db import migrations
import shortuuid.django_fields


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0011_alter_paidevents_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="paidevents",
            name="invitation_code",
            field=shortuuid.django_fields.ShortUUIDField(
                alphabet="0123456789",
                auto_created=True,
                editable=False,
                length=10,
                max_length=10,
                prefix="",
                unique=True,
                verbose_name="UUID для приглашения на мероприятие",
            ),
        ),
        migrations.AddField(
            model_name="privateevents",
            name="invitation_code",
            field=shortuuid.django_fields.ShortUUIDField(
                alphabet="0123456789",
                auto_created=True,
                editable=False,
                length=10,
                max_length=10,
                prefix="",
                unique=True,
                verbose_name="UUID для приглашения на мероприятие",
            ),
        ),
    ]
