# Generated by Django 4.0.8 on 2023-05-01 09:32

from django.conf import settings
from django.db import migrations
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0012_alter_eventregistrations_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregistrations',
            name='shortuuid',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='0123456789', auto_created=True, length=10, max_length=10, prefix='', unique=True, verbose_name='UUID записи на мероприятие'),
        ),
        migrations.AlterUniqueTogether(
            name='eventregistrations',
            unique_together={('event_id', 'user_id')},
        ),
    ]
