# Generated by Django 4.0.8 on 2023-05-01 16:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('events', '0013_eventregistrations_shortuuid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='visitors',
            field=models.ManyToManyField(blank=True, through='events.EventRegistrations', to=settings.AUTH_USER_MODEL, verbose_name='Зарегестрированные на мероприятие пользователи'),
        ),
    ]
