# Generated by Django 4.2.1 on 2023-05-09 14:09

from django.db import migrations
import shortuuid.django_fields


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0013_alter_privateevents_invitation_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paidevents",
            name="invitation_code",
            field=shortuuid.django_fields.ShortUUIDField(
                alphabet="0123456789",
                auto_created=True,
                length=10,
                max_length=10,
                prefix="",
                unique=True,
                verbose_name="UUID для приглашения на мероприятие",
            ),
        ),
    ]
