# Generated by Django 4.2.1 on 2023-05-12 20:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0015_alter_paideventregistrations_payment_link_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="events",
            name="is_avaliable",
            field=models.BooleanField(
                default=True, verbose_name="Доступность мероприятия"
            ),
        ),
        migrations.AddField(
            model_name="paidevents",
            name="is_avaliable",
            field=models.BooleanField(
                default=True, verbose_name="Доступность мероприятия"
            ),
        ),
        migrations.AddField(
            model_name="privateevents",
            name="is_avaliable",
            field=models.BooleanField(
                default=True, verbose_name="Доступность мероприятия"
            ),
        ),
    ]
