# Generated by Django 4.2.1 on 2023-05-14 11:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("events", "0017_remove_events_is_avaliable_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="eventregistrations",
            name="event_user_id_unique",
        ),
        migrations.RemoveConstraint(
            model_name="paideventregistrations",
            name="paid_event_user_id_unique",
        ),
        migrations.RemoveConstraint(
            model_name="privateeventregistrations",
            name="private_event_user_id_unique",
        ),
        migrations.RenameField(
            model_name="eventregistrations",
            old_name="event_id",
            new_name="event",
        ),
        migrations.RenameField(
            model_name="eventregistrations",
            old_name="inviting_user_id",
            new_name="inviting_user",
        ),
        migrations.RenameField(
            model_name="eventregistrations",
            old_name="user_id",
            new_name="user",
        ),
        migrations.RenameField(
            model_name="paideventregistrations",
            old_name="event_id",
            new_name="event",
        ),
        migrations.RenameField(
            model_name="paideventregistrations",
            old_name="inviting_user_id",
            new_name="inviting_user",
        ),
        migrations.RenameField(
            model_name="paideventregistrations",
            old_name="user_id",
            new_name="user",
        ),
        migrations.RenameField(
            model_name="privateeventregistrations",
            old_name="event_id",
            new_name="event",
        ),
        migrations.RenameField(
            model_name="privateeventregistrations",
            old_name="inviting_user_id",
            new_name="inviting_user",
        ),
        migrations.RenameField(
            model_name="privateeventregistrations",
            old_name="user_id",
            new_name="user",
        ),
        migrations.AlterUniqueTogether(
            name="eventregistrations",
            unique_together={("event", "user")},
        ),
        migrations.AlterUniqueTogether(
            name="paideventregistrations",
            unique_together={("event", "user")},
        ),
        migrations.AlterUniqueTogether(
            name="privateeventregistrations",
            unique_together={("event", "user")},
        ),
        migrations.AddConstraint(
            model_name="eventregistrations",
            constraint=models.UniqueConstraint(
                fields=("event", "user"), name="event_user_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="paideventregistrations",
            constraint=models.UniqueConstraint(
                fields=("event", "user"), name="paid_event_user_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="privateeventregistrations",
            constraint=models.UniqueConstraint(
                fields=("event", "user"), name="private_event_user_unique"
            ),
        ),
    ]
