# Generated by Django 4.2.1 on 2023-05-15 23:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0019_rename_category_id_events_category_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="events",
            options={
                "verbose_name": "мероприятие",
                "verbose_name_plural": "Мероприятия",
            },
        ),
        migrations.AlterModelOptions(
            name="eventtypes",
            options={
                "verbose_name": "тип мероприятия",
                "verbose_name_plural": "Типы мероприятий",
            },
        ),
        migrations.AlterModelOptions(
            name="eventvenues",
            options={
                "verbose_name": "место проведения мероприятия",
                "verbose_name_plural": "Места проведения мероприятий",
            },
        ),
        migrations.AlterModelOptions(
            name="paidevents",
            options={
                "verbose_name": "платное мероприятие",
                "verbose_name_plural": "Платные мероприятия",
            },
        ),
        migrations.AlterModelOptions(
            name="privateevents",
            options={
                "verbose_name": "приватное мероприятие",
                "verbose_name_plural": "Приватные мероприятия",
            },
        ),
    ]
