# Generated by Django 4.0.8 on 2023-05-16 10:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0021_alter_events_visitors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paidevents',
            name='visitors',
            field=models.ManyToManyField(blank=True, limit_choices_to={'paideventregistrations__is_invitation_accepted': True}, through='events.PaidEventRegistrations', to=settings.AUTH_USER_MODEL, verbose_name='Зарегестрированные на платное мероприятие пользователи'),
        ),
        migrations.AlterField(
            model_name='privateevents',
            name='visitors',
            field=models.ManyToManyField(blank=True, limit_choices_to={'privateeventregistrations__is_invitation_accepted': True}, through='events.PrivateEventRegistrations', to=settings.AUTH_USER_MODEL, verbose_name='Зарегестрированные на приватное мероприятие пользователи'),
        ),
    ]
