# Generated by Django 4.2.1 on 2023-05-17 20:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("events", "0022_alter_paidevents_visitors_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="events",
            options={
                "ordering": ("-id",),
                "verbose_name": "мероприятие",
                "verbose_name_plural": "Мероприятия",
            },
        ),
        migrations.AlterModelOptions(
            name="paidevents",
            options={
                "ordering": ("-id",),
                "verbose_name": "платное мероприятие",
                "verbose_name_plural": "Платные мероприятия",
            },
        ),
        migrations.AlterModelOptions(
            name="privateevents",
            options={
                "ordering": ("-id",),
                "verbose_name": "приватное мероприятие",
                "verbose_name_plural": "Приватные мероприятия",
            },
        ),
        migrations.AlterField(
            model_name="paidevents",
            name="visitors",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={
                    "paideventregistrations__is_invitation_accepted": True,
                    "paideventregistrations__payment_status": "PAID",
                },
                through="events.PaidEventRegistrations",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Зарегестрированные на платное мероприятие пользователи",
            ),
        ),
    ]
