# Generated by Django 4.2.1 on 2023-05-20 11:03

from django.db import migrations
import shortuuid.django_fields


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0023_alter_events_options_alter_paidevents_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="eventregistrations",
            old_name="is_invitation_accepted",
            new_name="is_registration_confirmed",
        ),
        migrations.RenameField(
            model_name="paideventregistrations",
            old_name="is_invitation_accepted",
            new_name="is_registration_confirmed",
        ),
        migrations.RenameField(
            model_name="privateeventregistrations",
            old_name="is_invitation_accepted",
            new_name="is_registration_confirmed",
        ),
        migrations.AlterField(
            model_name="paidevents",
            name="invitation_code",
            field=shortuuid.django_fields.ShortUUIDField(
                alphabet="0123456789",
                auto_created=True,
                length=10,
                max_length=10,
                prefix="",
                unique=True,
                verbose_name="UUID код для приглашения на мероприятие",
            ),
        ),
        migrations.AlterField(
            model_name="privateevents",
            name="invitation_code",
            field=shortuuid.django_fields.ShortUUIDField(
                alphabet="0123456789",
                auto_created=True,
                length=10,
                max_length=10,
                prefix="",
                unique=True,
                verbose_name="UUID код для приглашения на мероприятие",
            ),
        ),
    ]
