# Generated by Django 4.2.1 on 2023-05-20 11:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "events",
            "0024_rename_is_invitation_accepted_eventregistrations_is_registration_confirmed_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="events",
            name="visitors",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={
                    "eventregistrations__is_registration_confirmed": True
                },
                through="events.EventRegistrations",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Зарегестрированные на мероприятие пользователи",
            ),
        ),
        migrations.AlterField(
            model_name="paidevents",
            name="visitors",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={
                    "paideventregistrations__is_registration_confirmed": True,
                    "paideventregistrations__payment_status": "PAID",
                },
                through="events.PaidEventRegistrations",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Зарегестрированные на платное мероприятие пользователи",
            ),
        ),
        migrations.AlterField(
            model_name="privateevents",
            name="visitors",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={
                    "privateeventregistrations__is_registration_confirmed": True
                },
                through="events.PrivateEventRegistrations",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Зарегестрированные на приватное мероприятие пользователи",
            ),
        ),
    ]
